<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $products = array(
        //     array(
        //         "id" => 1,
        //         "name" => "IdeaPad Flex 5 14|AU7",
        //         "part_number" => "82R700E0UE",
        //         "series" => "Flex",
        //         "slug" => "ideapad-flex-5-14au7",
        //         "description" => "IdeaPad Flex 5 14IAU7,Intel® Core™ i7-1255U, 10C (2P + 8E) / 12T, P-core 1.7 / 4.7GHz,E-core 1.2 / 3.5GHz, 12MB,Integrated Intel Iris® Xe Graphics,Intel SoC Platform,16GB Soldered LPDDR4x-4266,Memory soldered to systemboard, no slots, dual-channel,(8GB or 16GB models),16GB soldered memory, not upgradable,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,10-point Multi-touch,Backlit, English (UK),Lenovo® Digital Pen,2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 110370.00,
        //         "discount_price" => 110370.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_Flex_5_14IAU7?M=82R700E0UE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:09:22",
        //         "updated_at" => "2024-09-25 15:11:16",
        //     ),
        //     array(
        //         "id" => 2,
        //         "name" => "IdeaPad 1 14|AU7",
        //         "part_number" => "82QC0061UE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-1-14au7",
        //         "description" => "IdeaPad 1 14IAU7,Intel® Core™ i5-1235U, 10C (2P + 8E) / 12T, P-core 1.3 / 4.4GHz,E-core 0.9 / 3.3GHz, 12MB,Integrated Intel Iris® Xe Graphics Functions as UHD Graphics,8GB Soldered DDR4-3200,Up to 16GB (8GB soldered + 8GB SO-DIMM) DDR4-3200,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,2Y Depot from 1Y Depot MEA DOS (CPN)",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 71500.00,
        //         "discount_price" => 71500.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_1_14IAU7?M=82QC0061UE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 2,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:10:47",
        //         "updated_at" => "2024-09-25 15:10:47",
        //     ),
        //     array(
        //         "id" => 3,
        //         "name" => "IdeaPad Slim 3 14|RH8",
        //         "part_number" => "83EL002SUE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-slim-3-14rh8",
        //         "description" => "IdeaPad Slim 3 14IRH8 Intel® Core™ i5-13420H, 8C (4P + 4E) / 12T, P-core 2.1 /4.6GHz, E-core 1.5 / 3.4GHz, 12MB,Integrated Intel® UHD Graphics,8GB Soldered LPDDR5-4800,Memory soldered to systemboard, no slots, single-channel (8GB models),8GB soldered memory, not upgradable,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,One drive, up to 1TB M.2 2242 SSD,SD Card Reader,High Definition (HD) Audio,HD 720p with Privacy ShutterNon-backlit, English (UK), 2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 62400.00,
        //         "discount_price" => 62400.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_Slim_3_14IRH8?M=83EL002SUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 2,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:13:40",
        //         "updated_at" => "2024-09-25 15:13:40",
        //     ),
        //     array(
        //         "id" => 4,
        //         "name" => "IdeaPad 1 14IAU7",
        //         "part_number" => "82RJ00F2UE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-1-14iau7",
        //         "description" => "Intel® Core™ i3-1215U, 6C (2P + 4E) / 8T, P-core 1.2 / 4.4GHz, E-core 0.9 / 3.3GHz, 10MB,8GB Soldered DDR4-3200,256GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,Integrated Intel® UHD Graphics,Intel® SoC Platform,Up to 16GB (8GB soldered + 8GB SO-DIMM) DDR4-3200 offering,Non-backlit, English (UK),Stereo speakers, 1.5W x2, Dolby® Audio™,65W Round Tip (3-pin),SD Card Reader,2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 44590.00,
        //         "discount_price" => 44590.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_3_14IAU7?M=82RJ00F2UE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 1,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:17:51",
        //         "updated_at" => "2024-09-25 15:17:51",
        //     ),
        //     array(
        //         "id" => 5,
        //         "name" => "IdeaPad 1 14IAU7",
        //         "part_number" => "82QC0023UE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-1-14iau7-1",
        //         "description" => "IdeaPad 1 14IAU7 ,Intel® Core™ i3-1215U, 6C (2P + 4E) / 8T, P-core 1.2 / 4.4GHz,E-core 0.9 / 3.3GHz, 10MB,Integrated Intel UHD Graphics,4GB Soldered DDR4-3200,Up to 4GB (4GB soldered + empty SO-DIMM slot) DDR4-3200 offering,256GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,One drive, up to 512GB M.2 2242 SSD or 512GB M.2 2280 SSD,SD Card Reader,Non-backlit, English (UK),1-year, Courier or Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 41860.00,
        //         "discount_price" => 41860.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_1_14IAU7?M=82QC0023UE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 1,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:18:57",
        //         "updated_at" => "2024-09-25 15:18:57",
        //     ),
        //     array(
        //         "id" => 6,
        //         "name" => "IdeaPad 1 14|AU7",
        //         "part_number" => "82QC006LUE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-1-14au7-1",
        //         "description" => "IdeaPad 1 14IAU7,Intel® Core™ i3-1215U, 6C (2P + 4E) / 8T, P-core 1.2 / 4.4GHz,E-core 0.9 / 3.3GHz, 10MB,Integrated Intel UHD Graphics,Intel SoC Platform,8GB Soldered DDR4-3200,Up to 16GB (8GB soldered + 8GB SO-DIMM) DDR4-3200,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,One drive, up to 512GB M.2 2242 SSD or 512GB M.2 2280 SSD,SD Card Reader,Non-backlit, English (UK),1-year, Courier or Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 47060.00,
        //         "discount_price" => 47060.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_1_14IAU7?M=82QC006LUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 1,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:20:31",
        //         "updated_at" => "2024-09-25 15:20:31",
        //     ),
        //     array(
        //         "id" => 7,
        //         "name" => "IdeaPad 3 14|AU7",
        //         "part_number" => "82RJ0020UE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-3-14au7",
        //         "description" => "IdeaPad 3 14IAU7,Intel® Core™ i7-1255U, 10C (2P + 8E) / 12T, P-core 1.7 / 4.7GHz,C (2P + 8E) / 12T, P-core 1.7 / 4.7GHz,E-core 1.2 / 3.5GHz, 12MB,Integrated Intel® Iris® Xe Graphics Functions as UHD Graphics,8GB Soldered DDR4-3200,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,SD Card Reader,HD 720p with Privacy Shutter,14\" FHD (1920x1080) TN 250nits Anti-glare,1-year, Courier or Carry-in,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 0.00,
        //         "discount_price" => 0.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_3_14IAU7?M=82RJ0020UE",
        //         "status" => "Inactive",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:23:02",
        //         "updated_at" => "2024-09-25 15:23:02",
        //     ),
        //     array(
        //         "id" => 8,
        //         "name" => "Intel® Celeron® N4020",
        //         "part_number" => "82V6007TUE",
        //         "series" => "IdeaPad",
        //         "slug" => "intel-celeron-n4020",
        //         "description" => "Intel® Celeron® N4020 (2C / 2T, 1.1 / 2.8GHz, 4MB,Integrated Intel UHD Graphics 600,8GB SO-DIMM DDR4-2400,One DDR4 SO-DIMM slot,Up to 8GB (8GB SO-DIMM) DDR4-2400 offering,256GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,One drive, up to 512GB M.2 2242 SSD or 512GB M.2 2280 SSD,SD Card Reader,1-year, Courier or Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 0.00,
        //         "discount_price" => 0.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_1_14IGL7?M=82V6007TUE",
        //         "status" => "Inactive",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 4,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:24:23",
        //         "updated_at" => "2024-09-25 15:24:23",
        //     ),
        //     array(
        //         "id" => 9,
        //         "name" => "IdeaPad 1 14IGL7",
        //         "part_number" => "82V6008MUE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-1-14igl7",
        //         "description" => "IdeaPad 1 14IGL7,Intel® Celeron® N4020 (2C / 2T, 1.1 / 2.8GHz, 4MB),Inte,grated Intel® UHD Graphics 600,4GB Soldered DDR4-2400,256GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,SD Card Reader,14\" HD (1366x768) TN 220nits Anti-glare,HD 720p with Privacy Shutter,1-year, Courier or Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 27690.00,
        //         "discount_price" => 27690.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_1_14IGL7?M=82V6008MUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 4,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:25:48",
        //         "updated_at" => "2024-09-25 15:25:48",
        //     ),
        //     array(
        //         "id" => 10,
        //         "name" => "IdeaPad 1 14IGL7",
        //         "part_number" => "82V6008PUE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-1-14igl7-1",
        //         "description" => "IdeaPad 1 14IGL7, Intel® Celeron® N4020 (2C / 2T, 1.1 / 2.8GHz, 4MB),Integrated Intel® UHD Graphics 600,8GB SO-DIMM DDR4-2400,256GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,SD Card Reader,Stereo speakers, 1.5W x2, Dolby® Audio™,14\" HD (1366x768) TN 220nits Anti-glare,Camera privacy shutter,1-year, Courier or Carry-in.",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 29770.00,
        //         "discount_price" => 29770.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_1_14IGL7?M=82V6008PUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 4,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:28:16",
        //         "updated_at" => "2024-09-25 15:28:16",
        //     ),
        //     array(
        //         "id" => 11,
        //         "name" => "IdeaPad 1 14ALC7",
        //         "part_number" => "82R3007RUE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-1-14alc7",
        //         "description" => "IdeaPad 1 14ALC7,AMD Ryzen™ 5 5500U (6C / 12T, 2.1 / 4.0GHz, 3MB L2 / 8MB L3),Integrated AMD Radeon™ Graphics,8GB Soldered DDR4-3200,Up to 16GB (8GB soldered + 8GB SO-DIMM) DDR4-3200 offering,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,One drive, up to 1TB M.2 2242 SSD or 512GB M.2 2280 SSD,SD Card Reader,14\"\" FHD (1920x1080) TN 220nits Anti-glare,Camera privacy shutter,1-year, Courier or Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 49140.00,
        //         "discount_price" => 49140.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_1_14ALC7?M=82R3007RUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 5,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:29:24",
        //         "updated_at" => "2024-09-25 15:29:55",
        //     ),
        //     array(
        //         "id" => 12,
        //         "name" => "IdeaPad Slim 3 15ABR8",
        //         "part_number" => "82XM00DAUE",
        //         "series" => "IdeaPad",
        //         "slug" => "ideapad-slim-3-15abr8",
        //         "description" => "IdeaPad Slim 3 15ABR8,AMD Ryzen™ 7 7730U (8C / 16T, 2.0 / 4.5GHz, 4MB L2 / 16MB L3),Integrated AMD Radeon™ Graphics,8GB Soldered DDR4-3200,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,One drive, up to 1TB M.2 2242 SSD,SD Card Reader,15.6\"\" FHD (1920x1080) IPS 300nits Anti-glare,2Y Depot from 1Y Depot.",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 74620.00,
        //         "discount_price" => 74620.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/IdeaPad_Slim_3_15ABR8?M=82XM00DAUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 5,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:31:22",
        //         "updated_at" => "2024-09-25 15:31:22",
        //     ),
        //     array(
        //         "id" => 13,
        //         "name" => "Intel® Core™ i5-12450H",
        //         "part_number" => "82XV00TJUE",
        //         "series" => "LOQ 3 Series",
        //         "slug" => "intel-core-i5-12450h",
        //         "description" => "Intel® Core™ i5-12450H, 8C (4P + 4E) / 12T, P-core 2.0 / 4.4GHz, E-core 1.5 / 3.3GHz, 12MB,NVIDIA® GeForce RTX™ 2050 4GB GDDR6, Boost Clock,1575MHz, TGP 70W,1x 8GB SO-DIMM DDR5-4800,Two DDR5 SO-DIMM slots, dual-channel capable,Up to 16GB DDR5-4800 offering,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,White Backlit, English (UK), ,2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 78390.00,
        //         "discount_price" => 78390.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/LOQ_15IRH8?M=82XV00TJUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 2,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:33:43",
        //         "updated_at" => "2024-09-25 15:33:43",
        //     ),
        //     array(
        //         "id" => 14,
        //         "name" => "Legion Slim 5 16IRH8",
        //         "part_number" => "82YA00EXUE",
        //         "series" => "Legion Slim",
        //         "slug" => "legion-slim-5-16irh8",
        //         "description" => "Legion Slim 5 16IRH8,Intel® Core™ i7-13700H, 14C (6P + 8E) / 20T, P-core 2.4 /,5.0GHz, E-core 1.8 / 3.7GHz, 24MB,NVIDIA® GeForce RTX™ 4060 8GB GDDR6, Boost Clock,2370MHz, TGP 125W,Intel SoC Platform,2x 8GB SO-DIMM DDR5-5200,Two DDR5 SO-DIMM slots, dual-channel capable,Up to 32GB DDR5-5200 offering,1TB SSD M.2 2280 PCIe® 4.0x4 NVMe®,4-in-1 Card Reader,,2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 0.00,
        //         "discount_price" => 0.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/Legion_Slim_5_16IRH8?M=82YA00EXUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:34:50",
        //         "updated_at" => "2024-09-25 15:34:50",
        //     ),
        //     array(
        //         "id" => 15,
        //         "name" => "Legion Slim 5 16IRH8",
        //         "part_number" => "82YA00GEUE",
        //         "series" => "Legion Slim",
        //         "slug" => "legion-slim-5-16irh8-1",
        //         "description" => "Legion Slim 5 16IRH8, Intel® Core™ i7-13700H, 14C (6P + 8E) / 20T, P-core 2.4 /5.0GHz, E-core 1.8 / 3.7GHz, 24MB,NVIDIA® GeForce RTX™ 4060 8GB GDDR6, Boost Clock,2370MHz, TGP 125W,2x 8GB SO-DIMM DDR5-5200,Two DDR5 SO-DIMM slots, dual-channel capable,Up to 32GB DDR5-5200 offering,512GB SSD M.2 2280 PCIe® 4.0x4 NVMe®,4-in-1 Card Reader,2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in.",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 203580.00,
        //         "discount_price" => 203580.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/Legion_Slim_5_16IRH8?M=82YA00GEUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:36:14",
        //         "updated_at" => "2024-09-25 15:36:14",
        //     ),
        //     array(
        //         "id" => 16,
        //         "name" => "Yoga 7 14IRL8",
        //         "part_number" => "82YL008MUE",
        //         "series" => "Yoga",
        //         "slug" => "yoga-7-14irl8",
        //         "description" => "Yoga 7 14IRL8,Intel® Core™ i7-1355U, 10C (2P + 8E) / 12T, P-core 1.7 / 5.0GHz,,E-core 1.2 / 3.7GHz, 12MB,Integrated Intel Iris® Xe Graphics,16GB Soldered LPDDR5-5200,Memory soldered to systemboard, no slots, dual-channel,16GB soldered memory, not upgradable1TB SSD M.2 2242 PCIe® 4.0x4 NVMe®,One drive, up to 1TB M.2 2242 SSD,microSD Card Reader,Backlit, English (UK),Lenovo® Digital Pen,OGM, 10-point Multi-touch,Backlit, English (UK),,2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 136630.00,
        //         "discount_price" => 136630.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/Yoga_7_14IRL8?M=82YL008MUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:37:42",
        //         "updated_at" => "2024-09-25 15:37:42",
        //     ),
        //     array(
        //         "id" => 17,
        //         "name" => "Yoga 7 14IRL8",
        //         "part_number" => "82YL00AJUE",
        //         "series" => "Yoga",
        //         "slug" => "yoga-7-14irl8-1",
        //         "description" => "Yoga 7 14IRL8, Intel® Core™ i7-1360P, 12C (4P + 8E) / 16T, P-core 2.2 /,5.0GHz, E-core 1.6 / 3.7GHz, 18MB,Integrated Intel Iris® Xe Graphics,16GB Soldered LPDDR5-5200,16GB soldered memory, not upgradable,1TB SSD M.2 2242 PCIe® 4.0x4 NVMe®,microSD Card Reader,Backlit, English (UK),OGM, 10-point Multi-touch,Lenovo® Digital Pen,2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 166270.00,
        //         "discount_price" => 166270.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/Yoga_7_14IRL8?M=82YL00AJUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:39:11",
        //         "updated_at" => "2024-09-25 15:39:11",
        //     ),
        //     array(
        //         "id" => 18,
        //         "name" => "AMD Ryzen™ 7 7730U",
        //         "part_number" => "83B2008BUE",
        //         "series" => "Yoga",
        //         "slug" => "amd-ryzen-7-7730u",
        //         "description" => "AMD Ryzen™ 7 7730U (8C / 16T, 2.0 / 4.5GHz, 4MB L2 / 16MB L3),Integrated AMD Radeon™ Graphics,16GB Soldered LPDDR4x-4266,16GB soldered memory, not upgradable,512GB SSD M.2 2242 PCIe® 4.0x4 NVMe®,microSD Card Reader,Backlit, English (UK),Lenovo® Digital Pen,OGM, 10-point Multi-touch,2Y Courier/Carry-in upgrade from 1Y Courier/Carry-in,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 121550.00,
        //         "discount_price" => 121550.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/Yoga_6_13ABR8?M=83B2008BUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 5,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:40:42",
        //         "updated_at" => "2024-09-25 15:40:42",
        //     ),
        //     array(
        //         "id" => 19,
        //         "name" => "T14",
        //         "part_number" => "Think Pad T  series",
        //         "series" => "21F6005WUE",
        //         "slug" => "t14",
        //         "description" => "T14s,i7-1355U,16GB Base DDR5,512GB SSD M.2 2280 NVMe G4,Intel Iris Xe,Win 11 Pro 64,14.0\" WUXGA AG 300nits,FHD RGB Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , ,No Wired Ethernet,Y-SCR,Y-FPR,4 Cell 57Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG, , ,3 Year Carry-in,,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 191100.00,
        //         "discount_price" => 191100.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_T14s_Gen_4_Intel?M=21F6005WUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:42:29",
        //         "updated_at" => "2024-09-25 15:42:29",
        //     ),
        //     array(
        //         "id" => 20,
        //         "name" => "T14",
        //         "part_number" => "21F6005TUE",
        //         "series" => "Think Pad T  series",
        //         "slug" => "t14-1",
        //         "description" => "T14s,i7-1355U,16GB Base DDR5,512GB SSD M.2 2280 NVMe G4,Intel Iris Xe,Win 11 Pro 64,14.0\" WUXGA AG 300nits Touch,FHD RGB Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , ,No Wired Ethernet,Y-SCR,Y-FPR,4 Cell 57Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG, , ,3 Year Carry-in,,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 198120.00,
        //         "discount_price" => 198120.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_T14s_Gen_4_Intel?M=21F6005TUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:43:42",
        //         "updated_at" => "2024-09-25 15:43:42",
        //     ),
        //     array(
        //         "id" => 21,
        //         "name" => "T16",
        //         "part_number" => "21HH0057UE",
        //         "series" => "Think Pad T  series",
        //         "slug" => "t16",
        //         "description" => "T16,i7-1355U,16GB Base DDR5,512GB SSD M.2 2280 NVMe G4,Integrated,Win 11 Pro 64,16.0\" WUXGA AG 300nits,5M RGB+IR Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , , ,Y-SCR,Y-FPR,4 Cell 52.5Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG w/NumPad,, ,3 Year Carry-in,,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 184470.00,
        //         "discount_price" => 184470.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_T16_Gen_2_Intel?M=21HH0057UE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:45:25",
        //         "updated_at" => "2024-09-25 15:45:25",
        //     ),
        //     array(
        //         "id" => 22,
        //         "name" => "X1 Carbon",
        //         "part_number" => "21HM007KUE",
        //         "series" => "Think Pad X1 series",
        //         "slug" => "x1-carbon",
        //         "description" => "X1 Carbon,i7-1355U,16GB Base DDR5,512GB SSD M.2 2280 NVMe G4p,Intel Iris Xe,Win 11 Pro 64,14.0\" WUXGA AG 400nits,FHD IR Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , ,No Wired Ethernet,,Y-FPR,4 Cell 57Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG,, ,3 Year Carry-in,,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 249340.00,
        //         "discount_price" => 249340.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_X1_Carbon_Gen_11?M=21HM007KUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:46:57",
        //         "updated_at" => "2024-09-25 15:46:57",
        //     ),
        //     array(
        //         "id" => 23,
        //         "name" => "X1 Yoga",
        //         "part_number" => "21HQ006AUE",
        //         "series" => "Think Pad X1 Yoga series",
        //         "slug" => "x1-yoga",
        //         "description" => "X1 Yoga,i7-1355U,16GB Base DDR5,512GB SSD M.2 2280 NVMe G4p,Intel Iris Xe,Win 11 Pro 64,14.0\" WUXGA AR 400nits Touch,FHD IR Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , ,No Wired Ethernet,,Y-FPR,4 Cell 57Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG,, ,3 Year Carry-in,,Garaged Pen",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 266240.00,
        //         "discount_price" => 266240.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_X1_Yoga_Gen_8?M=21HQ006AUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:48:02",
        //         "updated_at" => "2024-09-25 15:48:02",
        //     ),
        //     array(
        //         "id" => 24,
        //         "name" => "X1 Yoga",
        //         "part_number" => "21HQ006CUE",
        //         "series" => "Think Pad X1 Yoga series",
        //         "slug" => "x1-yoga-1",
        //         "description" => "X1 Yoga,i7-1355U,16GB Base DDR5,1TB SSD M.2 2280 NVMe G4p,Intel Iris Xe,Win 11 Pro 64,14.0\" WUXGA AR 400nits Touch,FHD IR Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , ,No Wired Ethernet,,Y-FPR,4 Cell 57Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG,, ,3 Year Carry-in,,Garaged Pen",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 273130.00,
        //         "discount_price" => 273130.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_X1_Yoga_Gen_8?M=21HQ006CUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:50:13",
        //         "updated_at" => "2024-09-25 15:50:13",
        //     ),
        //     array(
        //         "id" => 25,
        //         "name" => "E16",
        //         "part_number" => "21JN0019UE",
        //         "series" => "Think Pad E series",
        //         "slug" => "e16",
        //         "description" => "E16,i7-1355U,8GB Base DDR4,512GB SSD M.2 2242 NVMe,Integrated,No OS,16.0\" WUXGA AG 300nits,FHD RGB Cam,Generic 2x2AX+BT,,,,,,Y-FPR,3 Cell 47Whr,65W USB-C 3PIN-UK,KB UK-ENG w/NumPad,, ,1 Year Carry-in,2Y Carry-in-HB,Topload Case",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 101140.00,
        //         "discount_price" => 101140.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_E16_Gen_1_Intel?M=21JN0019UE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:51:41",
        //         "updated_at" => "2024-09-25 15:51:41",
        //     ),
        //     array(
        //         "id" => 26,
        //         "name" => "X13",
        //         "part_number" => "21EX000WUE",
        //         "series" => "Think Pad X13",
        //         "slug" => "x13",
        //         "description" => "X13,i7-1355U,16GB Base DDR5,512GB SSD M.2 2280 NVMe G4,Intel Iris Xe,Win 11 Pro 64,13.3\" WUXGA AG 300nits,FHD RGB Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , ,No Wired Ethernet,Y-SCR,Y-FPR,3 Cell 41Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG, , ,3 Year Carry-in,,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 187850.00,
        //         "discount_price" => 187850.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_X13_Gen_4_Intel?M=21EX000WUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:53:03",
        //         "updated_at" => "2024-09-25 15:53:03",
        //     ),
        //     array(
        //         "id" => 27,
        //         "name" => "X13 Yoga",
        //         "part_number" => "21F2003AUE",
        //         "series" => "Think Pad X13 Yoga",
        //         "slug" => "x13-yoga",
        //         "description" => "X13 Yoga,i7-1355U,16GB Base DDR5,512GB SSD M.2 2280 NVMe G4,Intel Iris Xe,Win 11 Pro 64,13.3\" WUXGA AR 300nits Touch,FHD RGB Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , ,No Wired Ethernet,Y-SCR,Y-FPR,4 Cell 54.7Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG, , ,3 Year Carry-in,,Garaged Pen",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 211770.00,
        //         "discount_price" => 211770.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_X13_Yoga_Gen_4?M=21F2003AUE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:55:25",
        //         "updated_at" => "2024-09-25 15:55:25",
        //     ),
        //     array(
        //         "id" => 28,
        //         "name" => "X13 Yoga",
        //         "part_number" => "21F20032UE",
        //         "series" => "Think Pad X13 Yoga",
        //         "slug" => "x13-yoga-1",
        //         "description" => "X13 Yoga,i7-1355U,16GB Base DDR5,1TB SSD M.2 2280 NVMe G4,Intel Iris Xe,Win 11 Pro 64,13.3\" WUXGA AR 300nits Touch,FHD RGB Cam,Intel AX211 2x2AX 6E+BT,WWAN Upgradable, , ,No Wired Ethernet,Y-SCR,Y-FPR,4 Cell 54.7Whr,65W USB-C 3PIN-UK,BKLT KB UK-ENG, , ,3 Year Carry-in,,Garaged Pen",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 222040.00,
        //         "discount_price" => 222040.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkPad_X13_Yoga_Gen_4?M=21F20032UE",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 1,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 15:57:51",
        //         "updated_at" => "2024-09-25 15:57:51",
        //     ),
        //     array(
        //         "id" => 29,
        //         "name" => "Neo 50t G3,TWR",
        //         "part_number" => "11SE00DGUM",
        //         "series" => "Neo 50t G3",
        //         "slug" => "neo-50t-g3twr",
        //         "description" => "Neo 50t G3,TWR,,i3-12100,8GB DDR4,1TB 7200rpm,Integrated,No OS,DVD±RW,,Intel AX201 2x2AX+BT,3-in-1 Card Reader,,,,Parallel Port, ,Internal Speaker,Rear System Fan,,USB CLP UK-ENG,USB CLP MOUSE,PUB_POL/POR/ENG,1Yr Carry-in,  , 2Y Carry-in-HB",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 40430.00,
        //         "discount_price" => 40430.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkCentre_neo_50t?M=11SE00DGUM",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 2,
        //         "brand_id" => 1,
        //         "processor_id" => 1,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 16:06:13",
        //         "updated_at" => "2024-09-25 16:06:13",
        //     ),
        //     array(
        //         "id" => 30,
        //         "name" => "Neo 50s G4,SFF",
        //         "part_number" => "12JH00ELUM",
        //         "series" => "Neo 50s G4",
        //         "slug" => "neo-50s-g4sff",
        //         "description" => "Neo 50s G4,SFF, ,i5-12400,8GB DDR4,512GB SSD M.2 2280 NVMe G4,Integrated,No OS,DVD±RW, , ,7-in-1 Card Reader, , , ,Parallel Port,Serial Port ,Internal Speaker, , ,USB CLP UK-ENG,USB CLP MOUSE,PUB_POL/POR/ENG,1Yr Carry-in,  ,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 60060.00,
        //         "discount_price" => 60060.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkCentre_neo_50s_Gen_4?M=12JH00ELUM",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 2,
        //         "brand_id" => 1,
        //         "processor_id" => 2,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 16:07:38",
        //         "updated_at" => "2024-09-25 16:07:38",
        //     ),
        //     array(
        //         "id" => 31,
        //         "name" => "Neo 50s G4 SFF Intel Core i7-12700",
        //         "part_number" => "12JH00F1UM",
        //         "series" => "Neo 50s G4",
        //         "slug" => "neo-50s-g4-sff-intel-core-i7-12700",
        //         "description" => "Neo 50s G4 SFF Intel Core i7-12700, 12C (8P + 4E) / 20T, Max Turbo up to 4.9GHz, P-core 2.1 / 4.8GHz, E-core 1.6 / 3.6GHz, 25MB,1x 8GB UDIMM DDR4-3200,512GB SSD M.2 2280 PCIe® 4.0x4 NVMe® Opal 2.0,7-in-1 Card Reader,USB Calliope Keyboard, Black, English (UK),1-year, Courier or Carry-in",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 83460.00,
        //         "discount_price" => 83460.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkCentre_neo_50s_Gen_4?M=12JH00F1UM",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 2,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 16:09:05",
        //         "updated_at" => "2024-09-25 16:09:05",
        //     ),
        //     array(
        //         "id" => 32,
        //         "name" => "Neo 50t G3,TWR",
        //         "part_number" => "11SE00N8UM",
        //         "series" => "Neo 50t G3",
        //         "slug" => "neo-50t-g3twr-1",
        //         "description" => "Neo 50t G3,TWR,,i7-12700,8GB DDR4,512GB SSD M.2 2280 NVMe G4,Integrated,No OS,DVD±RW,,Intel AX201 2x2AX+BT,3-in-1 Card Reader,,,,Parallel Port, ,Internal Speaker,Rear System Fan,,USB CLP UK-ENG,USB CLP MOUSE,PUB_POL/POR/ENG,Intel Wi-Fi,1Yr Carry-in,  , 2Y Carry-in-HB",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 84760.00,
        //         "discount_price" => 84760.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkCentre_neo_50t?M=11SE00N8UM",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 2,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 16:10:17",
        //         "updated_at" => "2024-09-25 16:10:17",
        //     ),
        //     array(
        //         "id" => 33,
        //         "name" => "Neo 50t G3,TWR",
        //         "part_number" => "11SE00RFUM",
        //         "series" => "Neo 50t G3",
        //         "slug" => "neo-50t-g3twr-2",
        //         "description" => "Neo 50t G3,TWR,,i7-12700,8GB DDR4,512GB SSD M.2 2280 NVMe G4,Integrated,No OS,DVD±RW,, ,3-in-1 Card Reader,,,,Parallel Port, ,Internal Speaker,Rear System Fan,,USB CLP UK-ENG,USB CLP MOUSE,PUB_POL/POR/ENG,1Yr Carry-in,  ,",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 83460.00,
        //         "discount_price" => 83460.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkCentre_neo_50t?M=11SE00RFUM",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 2,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 16:11:30",
        //         "updated_at" => "2024-09-25 16:11:30",
        //     ),
        //     array(
        //         "id" => 34,
        //         "name" => "Neo 50t G3,TWR",
        //         "part_number" => "11SE00QVUM",
        //         "series" => "Neo 50t G3",
        //         "slug" => "neo-50t-g3twr-3",
        //         "description" => "Neo 50t G3,TWR,,i7-12700,16GB DDR4,512GB SSD M.2 2280 NVMe G4,Integrated,No OS,DVD±RW,,Intel AX201 2x2AX+BT,3-in-1 Card Reader,,,,Parallel Port, ,Internal Speaker,2-in-1 CPU fan,,USB CLP UK-ENG,USB CLP MOUSE,PUB_POL/POR/ENG,Intel Wi-Fi,1Yr Carry-in,  , 2Y Carry-in-HB",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 90220.00,
        //         "discount_price" => 90220.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkCentre_neo_50t?M=11SE00QVUM",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 2,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 16:13:08",
        //         "updated_at" => "2024-09-25 16:13:08",
        //     ),
        //     array(
        //         "id" => 35,
        //         "name" => "M70t Gen 4 Intel® Core™ i7-13700",
        //         "part_number" => "12DR002RUM",
        //         "series" => "M Series",
        //         "slug" => "m70t-gen-4-intel-core-i7-13700",
        //         "description" => "\"M70t Gen 4 Intel® Core™ i7-13700, 16C (8P + 8E) / 24T, Max Turbo up to 5.2GHz, P-core 2.1 / 5.1GHz, E-core 1.5 / 4.1GHz, 30MB,Graphics\r\nIntegrated Intel UHD Graphics 770,1x 8GB UDIMM DDR4-3200,Four DDR4 DIMM slots, dual-channel capabl,Up to 128GB DDR4-3200,512GB SSD M.2 2280 PCIe® 4.0x4 Value NVMe® Opal 2.0,1-year, Courier or Carry-in\"",
        //         "featured_image" => NULL,
        //         "images" => NULL,
        //         "selling_price" => 86190.00,
        //         "discount_price" => 86190.00,
        //         "instock" => 0.00,
        //         "is_featured" => 0,
        //         "is_sold" => 0,
        //         "link" => "https://psref.lenovo.com/Detail/ThinkCentre_M70t_Gen_4?M=12DR002RUM",
        //         "status" => "Active",
        //         "condition" => "New",
        //         "extras" => NULL,
        //         "category_id" => 2,
        //         "brand_id" => 1,
        //         "processor_id" => 3,
        //         "updated_by" => 1,
        //         "created_at" => "2024-09-25 16:14:37",
        //         "updated_at" => "2024-09-25 16:14:37",
        //     ),
        // );


        // foreach ($products as $productData) {
        //     $product = Product::where('name', $productData['name'])->first();
        //     if (!$product) {
        //         Product::create($productData);
        //     }
        // }
    }
}
